### ISSUE TITLE
Lista com as palavras

### ISSUE THREAD

**Issue by unwrap-nicolas** [AugustoPinheiro/diversity-slack-bot#3]
Não achei no repositorio a lista de termos/linguagem "racista, capacitista, machista e de caráter excludente", seria legal ter pras pessoas saberem e contribuirem com a lista.

**Comment by AugustoPinheiro** [comment]
> 

está no readme a planilha, solicita acesso lá?

**Comment by unwrap-nicolas** [comment]
eu vi que estava no readme, mas nao seria bom estar em um json ou algo assim no proprio repositorio? assim eu poderia abrir um pr com a contribuição por exemplo, mas se não for a ideia ta tudo certo tb :)

**Comment by AugustoPinheiro** [comment]
show, a ideia de estar em um sheet é para que todos em sua empresa possam dar sugestão sem necessariamente entender código, faz sentido?
